name: lite_flags
description: Minimal feature flags library for Dart & Flutter.
version: 0.0.1
homepage: https://github.com/jafcn09/lite_flags
repository: https://github.com/jafcn09/lite_flags
issue_tracker: https://github.com/jafcn09/lite_flags/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
